remote_theme: ankitsultana/researcher@gem
title: Zhenxiao Qi
url: "https://enlighten5.github.io"
baseurl: "https://enlighten5.github.io"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "index"
 - name: "Resume"
   link: "index"
 - name: "Contact"
   link: "contact"
 - name: "Teaching"
   link: "teaching"
